### ISSUE TITLE
ModuleNotFoundError: No module named 'Colorer' on PyPi

### ISSUE THREAD

**Issue by brainstorm** [bannsec/gallimaufry#1]
I was about to use your lib for some USB reveng stuff after reading your great docs/examples, but right after installing and going to use it I found:

```
$ python
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from Gallimaufry import USB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/romanvg/.miniconda/envs/usb/lib/python3.6/site-packages/Gallimaufry/__init__.py", line 2, in <module>
    from .USB import USB
  File "/Users/romanvg/.miniconda/envs/usb/lib/python3.6/site-packages/Gallimaufry/USB.py", line 1, in <module>
    import Colorer
ModuleNotFoundError: No module named 'Colorer'
```

Perhaps you just forgot to push it on pypi?:

```
(usb) $ ls -alhR ~/.miniconda/envs/usb/lib/python3.6/site-packages/Gallimaufry/Classes/ | grep -i Colorer
(usb) $ grep -ri Colorer ~/.miniconda/envs/usb/lib/python3.6/site-packages/Gallimaufry/*
/Users/romanvg/.miniconda/envs/usb/lib/python3.6/site-packages/Gallimaufry/USB.py:import Colorer
```

**Comment by brainstorm** [comment]
`pip install -e .` on the cloned repo gets me back on track, but still it would be nice to have in easily pip-installable from PyPi ;)

**Comment by bannsec** [comment]
Whoops. Yeah, I dev in editable mode. Will add that to the full install.

**Comment by bannsec** [comment]
actually... looks like i fixed that before but forgot to push to pypi? I just did a full venv install using pip install without -e and it ran correctly.

Can you try normal pip install . from the cloned repo? Will be pushing a new one in a few anyway.

**Comment by brainstorm** [comment]
Sure, that's what I'm doing ATM, thanks for keeping up with this module, handy! ;)
