### ISSUE TITLE
KeyError: 'usb.endpoint_number' on HEAD

### ISSUE THREAD

**Issue by brainstorm** [bannsec/gallimaufry#2]
After installing gallimaufry from the master branch from today and given the following info from my raw PCAP file:

```
('usb.bus_id', '2'),
('usb.device_address', '3'),
('usb.endpoint_address', '0x00000081'),
```

I'm getting the following error when running defining the following filter:

`packets = pcap.pcap_filter(bus_id=2, device_address=3, endpoint_number=1)`

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-4886fec114f5> in <module>()
----> 1 packets = pcap.pcap_filter(bus_id=2, device_address=3, endpoint_number=1)

~/.miniconda/envs/usb/lib/python3.6/site-packages/enforce/decorators.py in universal(wrapped, instance, args, kwargs)
    110                     _args = tuple()
    111 
--> 112             result = wrapped(*_args, **_kwargs)
    113 
    114             # we *only* return result if all type checks passed

~/dev/reveng-cnc/gallimaufry/Gallimaufry/USB.py in pcap_filter(self, bus_id, device_address, endpoint_number)
    126         if endpoint_number is not None:
    127             # Remember, the endpoint number is the lower 3 bits of the actual endpoint_number field
--> 128             pcap = [packet for packet in pcap if int(packet['_source']['layers']['usb']['usb.endpoint_number'],16) & 0b111 == endpoint_number]
    129 
    130         return pcap

~/dev/reveng-cnc/gallimaufry/Gallimaufry/USB.py in <listcomp>(.0)
    126         if endpoint_number is not None:
    127             # Remember, the endpoint number is the lower 3 bits of the actual endpoint_number field
--> 128             pcap = [packet for packet in pcap if int(packet['_source']['layers']['usb']['usb.endpoint_number'],16) & 0b111 == endpoint_number]
    129 
    130         return pcap

KeyError: 'usb.endpoint_number'
```

**Comment by brainstorm** [comment]
And here's the fix:

```
$ git diff
diff --git a/Gallimaufry/USB.py b/Gallimaufry/USB.py
index c5ca8fb..5e78484 100644
--- a/Gallimaufry/USB.py
+++ b/Gallimaufry/USB.py
@@ -125,7 +125,7 @@ class USB:

         if endpoint_number is not None:
             # Remember, the endpoint number is the lower 3 bits of the actual endpoint_number field
-            pcap = [packet for packet in pcap if int(packet['_source']['layers']['usb']['usb.endpoint_number'],16) & 0b111 == endpoint_number]
+            pcap = [packet for packet in pcap if int(packet['_source']['layers']['usb']['usb.endpoint_address'],16) & 0b111 == endpoint_number]

         return pcap
```

**Comment by bannsec** [comment]
I'm wondering if this is due to your wireshark version, actually. Two things:

1. Can you upload the pcap? I've tried the same type of filter on my install and it works fine.
1. Can you give it a shot with the docker image? (https://hub.docker.com/r/bannsec/gallimaufry/)

Steps to run it from the docker image would be:
```bash
$ sudo docker pull bannsec/gallimaufry
$ sudo docker run -it --rm -v $PWD/pcaps bannsec/gallimaufry
```

That will run it with a volume mount to your current directory moutned at /pcaps inside the container.

Also, what version of tshark are you using? `tshark --version`

**Comment by brainstorm** [comment]
Sure, here's the pcap, most probably today I'll capture more from the machine (running G-Code, just moving in one axis, etc...):

https://mega.nz/#F!rppB3JSC!q6MxsplmEnMOiRDCSRjwTw

And here's my current analysis in a jupyter notebook:

https://gist.github.com/brainstorm/ec3e8d40a203127e21048ce6d79c4fbc

And my local tshark version:

```
$ tshark --version
TShark (Wireshark) 2.4.3 (v2.4.3-0-g368ba1e)

Copyright 1998-2017 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, without POSIX capabilities, with GLib 2.36.0,
with zlib 1.2.5, with SMI 0.4.8, with c-ares 1.12.0, with Lua 5.2.4, with GnuTLS
3.4.17, with Gcrypt 1.7.7, with MIT Kerberos, with GeoIP, with nghttp2 1.14.0,
with LZ4, with Snappy, with libxml2 2.9.4.

Running on Mac OS X 10.12.6, build 16G1212 (Darwin 16.7.0), with Intel(R)
Core(TM) i7-7Y75 CPU @ 1.30GHz (with SSE4.2), with 16384 MB of physical memory,
with locale en_US.UTF-8, with libpcap version 1.8.1 -- Apple version 67.60.2,
with GnuTLS 3.4.17, with Gcrypt 1.7.7, with zlib 1.2.8.

Built using llvm-gcc 4.2.1 (Based on Apple Inc. build 5658) (LLVM build
2336.9.00).
```

And here's an example session with your container, I changed your docker cmdlines slightly since `sudo` is not required here:

```
$ docker run -it --rm -v $PWD:/pcaps bannsec/gallimaufry
(gallimaufry) gallimaufry@ef1eb3ffa44a:~$ cd /
(gallimaufry) gallimaufry@ef1eb3ffa44a:/$ ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  pcaps  proc  root  run  sbin  srv  sys  tmp  usr  var
(gallimaufry) gallimaufry@ef1eb3ffa44a:/$ ls pcaps/
1.nc                                bessie_gcode_1.csv   bessie_gcode_1.ulz         bessie_homing_usblizer.ulz  bessie_spindle_usblizer.csv  spindle_bessie_usblizer.ulz
XHC Mach3 CNC USB comms dump.ipynb  bessie_gcode_1.pcap  bessie_homing_usbcap.pcap  bessie_homing_usblyzer.csv  reveng.txt
(gallimaufry) gallimaufry@ef1eb3ffa44a:/$ cd pcaps/
(gallimaufry) gallimaufry@ef1eb3ffa44a:/pcaps$ ls
1.nc                                bessie_gcode_1.csv   bessie_gcode_1.ulz         bessie_homing_usblizer.ulz  bessie_spindle_usblizer.csv  spindle_bessie_usblizer.ulz
XHC Mach3 CNC USB comms dump.ipynb  bessie_gcode_1.pcap  bessie_homing_usbcap.pcap  bessie_homing_usblyzer.csv  reveng.txt
(gallimaufry) gallimaufry@ef1eb3ffa44a:/pcaps$ ipython
Python 3.5.3 (default, Sep 14 2017, 22:58:41)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from Gallimaufry.USB import USB
   ...:

In [2]: usb = ("./bessie_homing_usbcap.pcap")

In [3]: usb
Out[3]: './bessie_homing_usbcap.pcap'

In [4]: usb = USB("./bessie_homing_usbcap.pcap")

In [5]: usb
Out[5]: <USB packets=740>

In [6]: usb.devices
Out[6]: []
```

**Comment by bannsec** [comment]
So that seems correct. Looking at your pcap, you did not capture any device descriptors (or any other descriptors for that matter). Without the descriptors, Gallimaufry cannot auto identify what Devices are attached. The pcap filter does seem to work:

```python
In [9]: len(pcap.pcap_filter(bus_id=2, device_address=3, endpoint_number=1))
Out[9]: 718
```

I'm not sure what type of USB traffic this is. Seems to be a bunch of USB interrupts in, but doesn't look to be Keyboard. At the moment, the only parser for extracting data that I have written is for USB keyboard.

**Comment by brainstorm** [comment]
Thanks for checking it out! What should I do to capture the descriptors with USBPcap? I've tried steps 1 and 2 in the following tutorial:

http://desowin.org/usbpcap/tour.html

Do you have a better way to do that?

Thanks in advance! Closing the issue and reverting my change since it doesn't make sense, thanks for the explanation ;)

**Comment by bannsec** [comment]
So i think your change is valid, actually. One of the challenges with integrating with tshark is that if tshark changes the field names and such, it can affect this library. Not sure right now how to best handle that, but it's one of the main reasons to use the Docker version of this tool.

For capturing the descriptors, USB devices will sporadically send them. However, you should be able to induce your device to send it by starting your PCAP dump prior to plugging in the device. When you plug it in, it should send over the descriptors as one of the first actions.

**Comment by brainstorm** [comment]
Gotcha, I'll try to replug the device after selecting endpoints and such (Step 1 on tutorial).

Do you use other capture programs/gear for your analysis? Just curious.

**Comment by bannsec** [comment]
Nah, just Wireshark. https://wiki.wireshark.org/CaptureSetup/USB

**Comment by brainstorm** [comment]
Thanks for the hints! I've uploaded the new PCAPs (if you are curious and/or want to use them as examples) and physically disconnected and reconnected the device right after starting the capture with `USBPcapCMD.exe`. Now `pcap.devices` reads correctly:

`[<Silicon Labs Unknown... v1.0.0 USB2.0.0 bus_id=2 address=2>]`

I'm aware that there's only the Keyboard HID "dissector" for now... so far this [CNC device](https://en.wikipedia.org/wiki/Numerical_control) sends what seems to be motor encoder positions (from the device to the host) and some sort of non-ascii [nor grbl](https://github.com/grbl/grbl/wiki/Interfacing-with-Grbl) nor [smoothieboard](https://github.com/Smoothieware/Smoothieware/blob/edge/src/modules/communication/GcodeDispatch.cpp) "open" commands but instead some sort of [proprietary Mach3 commands](https://twitter.com/braincode/status/975305296363925505) from the host to the device... no [G-Code](https://en.wikipedia.org/wiki/G-code) AFAICT so far in the URB interrupt's `usb.capdata`.

**Comment by bannsec** [comment]
Awesome. So I actually will use this as an example of when having string descriptors is helpful. I just added string descriptors to the `print(pcap.summary)`, so it becomes a bit more apparent what you're dealing with:

```
Devices
-------

    Silicon Labs - Unknown...
    -------------------------
    bus_id: 2
    device_address: 2
    device_version: 1.0.0
    bluetooth_version: 2.0.0
    packets: 3044
    string descriptors:
        1. XHC MACH3 CARD
```

Also, i've sync'd pypi with the current version now so you shouldn't have to git clone.

**Comment by brainstorm** [comment]
Great! Thanks for the updates, I've pulled in your changes, fixed a couple of pandas mishaps and the plots are starting to make sense now (scroll towards the end for how it looks like through a session):

https://gist.github.com/brainstorm/ec3e8d40a203127e21048ce6d79c4fbc

Still have to figure out a few other bits on the protocol, but those nice smooth plots do look like position reporting **(from device to host)**.

We'll see if I can actually figure out the commands sent **from the host to the device** :)

**Comment by brainstorm** [comment]
Also noticed that after using the new PyPi-packaged gallimaufry today, my change mentioned earlier is not there:

https://github.com/bannsec/gallimaufry/issues/2#issuecomment-373959558

I would do a PR, but it's just a one line change and then reupload the Docker(file), right?

Thanks a lot in advance!

**Comment by bannsec** [comment]
So, it's a bit more complicated as changing that as you mentioned would break the other instances of Gallimaufry (to include the Docker built one).

That said, I've added logic to try to dynamically determine the correct field name. Can you try installing this locally with your version of tshark. I will push a new version to pypi once you confirm the update fixes your issue.

**Comment by brainstorm** [comment]
Yeah, works now!

**Comment by bannsec** [comment]
sounds good. pushed version 0.0.3
