### ISSUE TITLE
Expected 1 Descriptors, why?

### ISSUE THREAD

**Issue by brainstorm** [bannsec/gallimaufry#4]
I would guess that other devices are as strange (if not more) than mine?

<img width="1025" alt="skarmavbild 2018-03-21 kl 21 54 50" src="https://user-images.githubusercontent.com/175587/37797857-1d00777a-2e6f-11e8-8daf-2b238970f64b.png">

This is the output of `pcap.summary`, the CNC device seems to use 2 descriptors, one for host to device communication and the other way around:

```
PCAP: /Users/romanvg/dev/reveng-cnc/dumps/pcap/bessie_homing_with_descriptors.pcap
Total Packets: 3105

Devices
-------

    Silicon Labs - Unknown...
    -------------------------
    bus_id: 2
    device_address: 2
    device_version: 1.0.0
    bluetooth_version: 2.0.0
    packets: 3044
    string descriptors:
        1. XHC MACH3 CARD
    
    Configurations
    --------------
    
        Configuration 1
        ---------------
        bNumInterfaces = 2
        self_powered = True
        remote_wakeup = False
        
        Interfaces
        -----------
        
            Interface 0
            -----------
            Class: HID – Human Interface Device
            SubClass: No Subclass
            Protocol: None
            
            Endpoints
            ---------
            
                Endpoint 1
                ----------
                direction: In
                transfer_type: Interrupt
                packets: 2981
        
            Interface 1
            -----------
            Class: HID – Human Interface Device
            SubClass: No Subclass
            Protocol: None
            
            Endpoints
            ---------
            
                Endpoint 2
                ----------
                direction: Out
                transfer_type: Interrupt
                packets: 32
```

In my last iteration (revision 5) of the analysis I'm exploring precisely that, URB comms from host to device, scroll down for saw pattern plot and histogram:

https://gist.github.com/brainstorm/ec3e8d40a203127e21048ce6d79c4fbc

**Comment by bannsec** [comment]
Sorry, haven't had a chance to look at this yet. I do recall seeing some of those in my own testing as well. I _believe_ it's usually due to the USB device simply re-sending the device/Endpoint/etc descriptor multiple times and shouldn't cause any actual issues.

Definitely looks like you're doing some neat exploration. Is the error causing any issues that you can tell?

**Comment by brainstorm** [comment]
Hey, no worries, as you mention it is indeed that multiple descriptors were sent during that particular capture. I did a new capture yesterday (moving just one axis on the CNC, also uploaded to mega.nz if you want to have a look at it) and only one descriptor shows up in the PCAP dump, so I will close this issue.
